### ISSUE TITLE
VBoxManage: error: RawFile#0 failed to create the raw output file /home/tlittle/.baker/micro1.log (VERR_FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by toddinpal** [ottomatica/slim#135] opened 2020-05-20 20:20 UTC
Just tried building and running under VirtualBox the alpine3.9-simple sample and I get the following when I try to run the image:
$ slim run micro1 alpine3.9-simple
/home/tlittle/.slim/registry/alpine3.9-simple/slim.iso
Searching between ports 2002 and 2999 for ssh on localhost for this vm.
Excluding the following ports already used by VirtualBox VMS: 
Port 2002 is available for ssh on localhost!
Executing VBoxManage createvm --name "micro1" --register
Executing VBoxManage modifyvm "micro1" --memory 1024 --cpus 1
Executing VBoxManage storagectl "micro1" --name IDE --add ide
Executing VBoxManage storageattach micro1 --storagectl IDE --port 0 --device 0 --type dvddrive --medium "/home/tlittle/.slim/registry/alpine3.9-simple/slim.iso"
Executing VBoxManage modifyvm micro1  --uart1 0x3f8 4 --uartmode1 file /home/tlittle/.baker/micro1.log
Executing VBoxManage modifyvm micro1 --nic1 nat
Executing VBoxManage modifyvm micro1 --nictype1 virtio
Executing VBoxManage modifyvm micro1 --natpf1 "guestssh,tcp,,2002,,22"
Executing VBoxManage sharedfolder add micro1 --name "vbox-share-0" --hostpath "/home/tlittle/slim/images/alpine3.9-simple" 
Executing VBoxManage sharedfolder add micro1 --name "vbox-share-1" --hostpath "/" 
Executing VBoxManage startvm micro1 --type emergencystop
Executing VBoxManage startvm micro1 --type headless
=> exec error: { Error: Command failed: VBoxManage startvm micro1 --type headless
VBoxManage: error: RawFile#0 failed to create the raw output file /home/tlittle/.baker/micro1.log (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'VBoxManage startvm micro1 --type headless' }
ssh -i /home/tlittle/.slim/baker_rsa root@127.0.0.1 -p 2002 -o StrictHostKeyChecking=no

Should I have to create that log file manually?

-tl

**Comment by chrisparnin** [comment] 2020-05-20 20:29
This is caused by this directory not existing "/home/tlittle/.baker/".
**Temporary workaround is to create that directory**. Are you using older version of Virtual Box?

**Comment by chrisparnin** [comment] 2020-05-20 20:30
Related code is here:
https://github.com/ottomatica/node-virtualbox/blob/4ca675bc5055a9ab7eb59881215c76c9eeb3063e/lib/VBoxProvider.js#L33

**Comment by toddinpal** [comment] 2020-05-20 20:30
VirtualBox Version 6.1.8 r137981 (Qt5.6.1) which I think is the latest.

**Comment by chrisparnin** [comment] 2020-05-20 20:31
Ya, it's the other way around, using newest^

**Comment by chrisparnin** [comment] 2020-05-20 20:41
Published quick fix in the node-virtualbox package (0.2.4)
https://www.npmjs.com/package/node-virtualbox

**Comment by toddinpal** [comment] 2020-05-20 20:46
Cool!  Is there a reason there isn't a start command to start a vm that was previously stopped?

**Comment by chrisparnin** [comment] 2020-05-20 20:50
Hmm... we had a pull request to add this... but never merged!

https://github.com/ottomatica/slim/pull/76

Can do that now...

**Comment by chrisparnin** [comment] 2020-05-20 20:53
The longer story is that we're investing in the front-end lifecycle of running VMs in this tool:
https://github.com/ottomatica/bakerx

We use `slim` to build and publish images, but `bakerx` to run them.

**Closed** 2020-05-20 23:28 UTC
